# .github/workflows/ci.yml
name: Python Tests + Allure
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r shell-log-parser/requirements.txt
      - name: Run tests (produce allure results)
        run: |
          pytest --maxfail=1 --disable-warnings -q --alluredir=allure-results
      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
